name: Build ZMK Workflow   # workflow 최상위 이름

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build ZMK        # job 이름 (optional)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install west
          pip install -r zephyr/scripts/requirements.txt

      - name: Initialize West and update modules
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Build left shield
        run: |
          west build -s zmk/app \
                     -d build/left \
                     -b nice_nano_v2 \
                     -- -DZMK_CONFIG=./config \
                        -DSHIELD=cck_ball_left \
                        -DBOARD_ROOT=./config/boards

      - name: Build right shield
        run: |
          west build -s zmk/app \
                     -d build/right \
                     -b nice_nano_v2 \
                     -- -DZMK_CONFIG=./config \
                        -DSHIELD=cck_ball_right \
                        -DBOARD_ROOT=./config/boards
